### ISSUE TITLE
[Compatibility] Exposure

### ISSUE THREAD

**Issue by Fyoncle** [PieKing1215/InvMoveCompats#14]
When using the Lightroom of the Exposure mod, you can go right and left in the photos in the developed film using A and D but InvMove also works when this happens, is compat planned for that?

**Comment by PieKing1215** [comment]
After you open the screen once you should be able to go to the config menu for InvMove -> movement tab -> unrecognized ui types, and there should be an option to disable movement for that specific screen

No plans atm to add default settings for screens from other mods. I originally was doing that in the legacy version of InvMove for a bunch of mods and it was unsustainable to maintain since it needed to be updated when mods add/move screen types.
The idea is that InvMoveCompats is specifically for things that don't work through the unrecognized screens system (ie. REI/JEI/EMI, Create's ponder keybind, etc)

**Comment by Fyoncle** [comment]
> After you open the screen once you should be able to go to the config menu for InvMove -> movement tab -> unrecognized ui types, and there should be an option to disable movement for that specific screen
> 
> No plans atm to add default settings for screens from other mods. I originally was doing that in the legacy version of InvMove for a bunch of mods and it was unsustainable to maintain since it needed to be updated when mods add/move screen types. The idea is that InvMoveCompats is specifically for things that don't work through the unrecognized screens system (ie. REI/JEI/EMI, Create's ponder keybind, etc)

Thanks ❤️

**Comment by Fyoncle** [comment]
Well since u don't wanna mess with pain, and since the config is more than enough, i'm closing the issue.
